script: |

  cd /home/ubuntu

  if [ ! -d "myapp" ]; then
    git clone https://github.com/amalpk531/cicd-test.git myapp
  fi

  cd myapp

  git pull origin main

  echo "${{ secrets.HARBOR_PASSWORD }}" | docker login 172.31.21.99 \
    -u "${{ secrets.HARBOR_USERNAME }}" \
    --password-stdin

  VERSION=$(date +%Y%m%d%H%M%S)

  docker build --no-cache \
    -t 172.31.21.99/test-lab/mysite:$VERSION \
    -t 172.31.21.99/test-lab/mysite:latest .

  docker push 172.31.21.99/test-lab/mysite:$VERSION

  docker push 172.31.21.99/test-lab/mysite:latest

  docker stop mysite || true

  docker rm mysite || true

  docker run -d \
    --name mysite \
    -p 8080:80 \
    172.31.21.99/test-lab/mysite:$VERSION
